version: '3.1'
services:

    brownie_atelier:
        image: mikuras/brownie_atelier_app:${APP_TAG}
        container_name: brownie_atelier_app
        # restart: always
        networks:
            - default
        extra_hosts:
            # - "host.docker.internal:host-gateway"         # windows上のサービスに接続する場合
            - "host.docker.internal:${HOST_OS_IP_ADDRESS}"  # wsl2上のサービスに接続する場合
        volumes:
            - $PWD/data:$HOME/BrownieAtelier/data
            - ${LOCAL_MONGO_KEY_DIR}:$HOME/mongo-key
        command: ${CONTAINER_START_COMMAND}
        environment:
            # mongoDB接続情報
            BROWNIE_ATELIER_MONGO__MONGO_SERVER: ${BROWNIE_ATELIER_MONGO__MONGO_SERVER}
            BROWNIE_ATELIER_MONGO__MONGO_PORT: ${BROWNIE_ATELIER_MONGO__MONGO_PORT}
            BROWNIE_ATELIER_MONGO__MONGO_USE_DB: ${BROWNIE_ATELIER_MONGO__MONGO_USE_DB}
            BROWNIE_ATELIER_MONGO__MONGO_USER: ${BROWNIE_ATELIER_MONGO__MONGO_USER}
            BROWNIE_ATELIER_MONGO__MONGO_PASS: ${BROWNIE_ATELIER_MONGO__MONGO_PASS}
            BROWNIE_ATELIER_MONGO__MONGO_TLS: ${BROWNIE_ATELIER_MONGO__MONGO_TLS}
            BROWNIE_ATELIER_MONGO__MONGO_TLS_CA_FILE: ${BROWNIE_ATELIER_MONGO__MONGO_TLS_CA_FILE}
            BROWNIE_ATELIER_MONGO__MONGO_TLS_CERTTIFICATE_KEY_FILE: ${BROWNIE_ATELIER_MONGO__MONGO_TLS_CERTTIFICATE_KEY_FILE}
            # Brownie atelier noticeの設定 (slack)
            BROWNIE_ATELIER_NOTICE__SLACK_TOKEN: ${BROWNIE_ATELIER_NOTICE__SLACK_TOKEN}         
            BROWNIE_ATELIER_NOTICE__SLACK_CHANNEL_ID__ERROR: ${BROWNIE_ATELIER_NOTICE__SLACK_CHANNEL_ID__ERROR}         
            BROWNIE_ATELIER_NOTICE__SLACK_CHANNEL_ID__NOMAL: ${BROWNIE_ATELIER_NOTICE__SLACK_CHANNEL_ID__NOMAL}
            # prefectの環境設定
            PREFECT_API_URL: ${PREFECT_API_URL}
            PREFECT__API_KEY: ${PREFECT__API_KEY}
            PREFECT__WORK_SPACE: ${PREFECT__WORK_SPACE}
            PREFECT__WORK_POOL: ${PREFECT__WORK_POOL}
            # PREFECT_LOGGING_LEVEL: "INFO"
            # PREFECT_LOGGING_SERVER_LEVEL: "INFO"
            # PREFECT_LOGGING_INTERNAL_LEVEL: "INFO"
            PREFECT__DATA: "/home/${CONTAINER_USER}/BrownieAtelier/data"
            # Scrapyの環境設定
            # SCRAPY_SETTINGS_MODULE: "news_crawl.settings"
            SCRAPY__LOG_LEVEL: ${SCRAPY__LOG_LEVEL}
            # github actions unit testのスクリプトで使用
            PREFECT_RUN_SCRIPT: ${PREFECT_RUN_SCRIPT}

# 既存のネットワークbrownie-atelier-netを利用する。
networks:
  default:
    external:
      name: brownie-atelier-net
